### ISSUE TITLE
Problem 7 Issue

### ISSUE THREAD

**Issue by eitanlees** [slee5777/Dyalog_2022_Competition#1]
I figured out the issue with problem 7. There was a typo in the solution you copied. You wrote the "Not Equal" symbol when it should be the "Slash Bar" symbol. 

```
E ← (⊃,/)((≢⊢⍤/+≠÷≢)¨⍳⍨⍥,⊆⍳∘≢)        ⍝ Incorrect
E ← (⊃,/)((≢⊢⍤/+⌿÷≢)¨⍳⍨⍥,⊆⍳∘≢)        ⍝ Correct 
```

Unfortunately, GitHub doesn't handel the Unicode fonts so well in these comments. 

Thanks again for putting these solutions together!

**Comment by slee5777** [comment]
Thank you for spotting the error.  Fixed now.  [fe2c49d](https://github.com/slee5777/Dyalog_2022_Competition/commit/fe2c49d11d762084d81d448fba9b499ecb2ae01e)
